owner: Sparklify-Ai # GitHub username
repo: StatusPage # GitHub repository name
sites: # List of endpoints to track
  - name: Google
    url: https://www.google.com
status-website:
  baseUrl: /StatusPage # where "repo" is your repository name
  name: Sparklify Ai
  logoUrl: https://i.imgur.com/DGJEUoX.png
  favicon: https://i.imgur.com/DGJEUoX.png
  customHeadHtml: '<script src="https://cdn.counter.dev/script.js" data-id="76682767-fda2-450b-a1c9-7da71a1785a6" data-utcoffset="-4"></script>'
