owner: Sparklify-Ai # GitHub username
repo: StatusPage # GitHub repository name
sites: # List of endpoints to track
  - name: Google
    url: https://www.google.com
status-website:
  baseUrl: /StatusPage # where "repo" is your repository name
  name: Sparklify Ai
