owner: Sparklify-Ai # GitHub username
repo: StatusPage # GitHub repository name
sites: # List of endpoints to track
  - name: Google
    url: https://www.google.com
status-website:
  baseUrl: /StatusPage # where "repo" is your repository name
  name: Sparklify Ai Status
  logoUrl: https://cdn.glitch.global/898bdc70-6b18-4456-a888-b1411c42afda/sparkles
  favicon: https://cdn.glitch.global/898bdc70-6b18-4456-a888-b1411c42afda/sparkles
  customHeadHtml: '<script src="https://cdn.counter.dev/script.js" data-id="76682767-fda2-450b-a1c9-7da71a1785a6" data-utcoffset="-4"></script>'
  metaTags:
    - name: "title"
    content: "Is Sparklify Ai down? Check the Sparklify Ai status page."
    - name: "keywords"
    content: "Sparklify Ai, Sparklify Ai Status",
    - name: "robots"
    content: "noindex, nofollow"
    - name: "language"
    content: "English"
    - name: "author"
    content: "Sparklify Ai"
  robotsText: "User-agent: * \n Disallow: /"
  navbar:
    - title: Website
      href: https://sparklify.glitch.me/
  links:
    - rel: stylesheet
    href: https://sparklify.glitch.me/statuspage/style.css
  scripts:
    - src: https://sparklify.glitch.me/statuspage/script.js
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
